# Generated by Django 3.1.4 on 2020-12-30 04:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('application_portal', '0003_auto_20201230_1210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application_attachment',
            name='User',
        ),
        migrations.AddField(
            model_name='application_attachment',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='applicant_education',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
