# Generated by Django 3.1.4 on 2020-12-30 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application_portal', '0005_auto_20201230_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant_details',
            name='marital_status',
            field=models.CharField(choices=[('Single', 'Single'), ('Married', 'Married')], max_length=10),
        ),
    ]
