# Generated by Django 3.1.4 on 2021-01-01 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application_portal', '0007_auto_20201231_1201'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicant_details',
            options={'verbose_name': 'Applicant Details', 'verbose_name_plural': 'Applicant Details'},
        ),
        migrations.AlterModelOptions(
            name='applicant_education',
            options={'verbose_name': 'Applicant Education', 'verbose_name_plural': 'Applicant Education'},
        ),
        migrations.AlterModelOptions(
            name='application_attachment',
            options={'verbose_name': 'Application Attachments', 'verbose_name_plural': 'Application Attachments'},
        ),
        migrations.AlterField(
            model_name='application_attachment',
            name='attachment_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
