# Generated by Django 3.1.4 on 2021-01-01 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application_portal', '0008_auto_20210101_2151'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicant_education',
            old_name='school',
            new_name='university',
        ),
        migrations.AlterField(
            model_name='application_attachment',
            name='attachment_file',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='File'),
        ),
    ]
