# Generated by Django 3.1.4 on 2021-01-01 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application_portal', '0010_auto_20210101_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant_education',
            name='gpa',
            field=models.FloatField(verbose_name='GPA'),
        ),
    ]
