# Generated by Django 3.1.4 on 2021-01-02 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application_portal', '0012_user_attributes_submitted_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant_details',
            name='dependents',
            field=models.IntegerField(blank=True, default=0, verbose_name='No. of Dependents'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='applicant_details',
            name='years_of_experience',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
