# Generated by Django 3.1.4 on 2021-01-03 09:10

import application_portal.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application_portal', '0014_auto_20210103_0245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application_attachment',
            name='description',
        ),
        migrations.AlterField(
            model_name='application_attachment',
            name='attachment_file',
            field=models.FileField(blank=True, null=True, upload_to=application_portal.models.user_attachment_path, verbose_name='File'),
        ),
    ]
