# Generated by Django 3.1.4 on 2021-01-03 20:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('application_portal', '0017_auto_20210104_0409'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user_attributes',
            new_name='application_attributes',
        ),
    ]
