# Generated by Django 3.1.4 on 2021-01-04 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application_portal', '0019_auto_20210104_0417'),
    ]

    operations = [
        migrations.DeleteModel(
            name='application_attributes',
        ),
    ]
